### PR TITLE
Handle multiple environments

### PR DESCRIPTION
**Pull request by MattiSG**
Import production environment from production server.

Use with `./start.sh mes-aides` (default `./start.sh` still works).

@jdesboeufs The upstart script used `/usr/local/bin/gunicorn --paster production.ini` rather than `paster serve`. What are the advantages or preferring `gunicorn`?

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Late 2014, [SciPy](http://www.scipy.org/) was used by some formula.
[SciPy](http://www.scipy.org/) is **single-threaded** and can't work in **multi-threaded** environment (memory corruption).
In production, `Paster` is multi-threaded so we ended with segfaults.
[gunicorn](http://gunicorn.org/) is **multi-processes**, so each [SciPy](http://www.scipy.org/) call was isolated from others.

Other reasons:
- [gunicorn](http://gunicorn.org/) is inspired by [unicorn](http://unicorn.bogomips.org/), work as **Node.js**, and can be easily integrated with **nginx** (reverse proxy)
- I was comfortable with the philosophy
- It worked. In Late 2014 I was not able to deploy with `Paster`

But there is no logs :(

**Comment by MattiSG** [comment]
Great, thanks a lot!!

Since SciPy has been removed and Paster now works, let's do the least work and have a single command for all env.

**Comment by jdesboeufs** [comment]
Yeah!
Having logs in production has no price.

**Comment by MattiSG** [comment]
Meh. Don't get too excited, it's not like we _actually_ had logs.

**Pull request merged**
